server:
  port: 8000



eureka:
  client:
    # 因为是服务消费端，所以自己不能注册
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/